// Generated by CodiumAI

describe('EditProducts', () => {

});

    // Verify that findOneAndUpdate method is called with correct parameters
    it('should call findOneAndUpdate method with correct parameters', () => {
      const req = {
        params: {
          id: '123'
        },
        body: {
          name: 'New Product',
          price: 10.99
        }
      };

      const res = {
        status: jest.fn().mockReturnThis(),
        json: jest.fn()
      };

      const findOneAndUpdateMock = jest.spyOn(ProductData, 'findOneAndUpdate');

      EditProducts(req, res);

      expect(findOneAndUpdateMock).toHaveBeenCalledWith(
        { id: '123' },
        { name: 'New Product', price: 10.99 },
        { new: true }
      );
    });

